<div id="custom-component" data-bind="scope:'customcomponentformjstest'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "#custom-component": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "customcomponentformjstest": {
                        "component": "Junior_Chapter03/js/knockoutTest"
                    }
                }
            }
        }
    }
    </script>

</div>
